### PR TITLE
[BUG FIX] Move Hybrid optimizer experiments from hanging in PROCESSING to ERROR while running with deleted judgment

### LINKED ISSUE #282: [BUG] Hybrid Optimizer Result Stuck in Processing
### What is the bug?
When the underlying judgment is deleted, the hybrid experiment status is not updated from the "processing" state

### How can one reproduce the bug?
We can run the `demo.sh` scripts then rerun the hybrid optimizer experiment after deleting the judgment that the experiment uses. 

### What is the expected behavior?
The hybrid experiment result should have its status set to "error". 

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by venkateshwaracholan**
Resolves #282 

Description
This PR fixes incorrect failure handling logic in HybridOptimizerExperimentProcessor.
Previously, an internal if(hasFailure.compareAndSet(false, true)) check within the async block prevented the caller’s failure flag from toggling correctly when a judgment processing error occurred.

Because hasFailure was passed by reference, this local check caused two issues:

- Caller-level failure handling in ExperimentRunningManager.java#handleFailure never triggered, since the flag was set too early inside the nested async scope.
- Suppressed error notifications.

The fix removes the redundant internal hasFailure toggle, allowing the caller’s handleFailure() method to correctly determine when to mark a failure and handle retries, metrics cleanup, or experiment continuation appropriately.

**Issues Resolved**

Fixes premature failure flag toggling in HybridOptimizerExperimentProcessor, which previously blocked upstream recovery logic.

**Testing**

- Verified that failures propagate correctly to the caller-level handleFailure() method.
- Confirmed no duplicate or missing onFailure() triggers.
- Validated normal judgment processing flow remains unaffected.

### CODE REVIEW

File: src/main/java/org/opensearch/searchrelevance/experiment/HybridOptimizerExperimentProcessor.java [hunk 1]
```diff
@@ -143,9 +143,7 @@ public void processHybridOptimizerExperiment(
                 listener
             );
         }).exceptionally(e -> {
-            if (hasFailure.compareAndSet(false, true)) {
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/searchrelevance/experiment/HybridOptimizerExperimentProcessor.java]: I don't think you should remove this pattern. This approach ensures that failure notification is a single instance. Think of scenario when multiple threads are calling `listener.onFailure()` at the same time, what is the behavior in such case?  
The real issue is in the error propagation chain between the processor and `ExperimentRunningManager`

**Review by martin-gaievski — DISMISSED** [review]
I think this change does not address the real issue. You need to check for empty judgment list and act on this accordingly, and leave current approach with atomic unchanged. The proper place for this change is in the method `processJudgmentsAsync`. Here is the skeleton of the possible fix:

```java
private CompletableFuture<Map<String, String>> processJudgmentsAsync(String queryText, List<String> judgmentList) {
    // ... existing code ...
    
    return CompletableFuture.allOf(judgmentFutures.toArray(new CompletableFuture[0])).thenApply(v -> {
        Map<String, String> docIdToScores = new HashMap<>();
        List<String> missingJudgments = new ArrayList<>();
        
        for (int i = 0; i < judgmentFutures.size(); i++) {
            try {
                SearchResponse response = judgmentFutures.get(i).join();
                // this is critical check - deleted judgments return 0 hits
                if (response.getHits().getTotalHits().value() == 0) {
                    missingJudgments.add(judgmentList.get(i));
                    log.error("Judgment {} not found (deleted or missing)", judgmentList.get(i));
                } else {
                    extractJudgmentScores(queryText, response, docIdToScores);
                }
            } catch (Exception e) {
                log.error("Failed to process judgment {}: {}", judgmentList.get(i), e.getMessage());
                missingJudgments.add(judgmentList.get(i));
            }
        }
        
        // Throw exception when judgments are missing to trigger ERROR state
        if (!missingJudgments.isEmpty()) {
            throw new IllegalStateException(
                String.format("Cannot proceed: %d judgment(s) missing or deleted: %s", 
                    missingJudgments.size(), missingJudgments)
            );
        }
        
        return docIdToScores;
    });
}
```

Your PR is also missing the tests, I think the scenario you're trying to fix is possible to reproduce using unit tests and mock objects

**Comment by martin-gaievski** [comment]
@venkateshwaracholan thank you for the detailed explanation and updated commit. I agree with your analysis and findings, and the latest addition of the AtomicBoolean flag gives confidence in a proper error propagation.

One addition is still needed though, if you can add test that checking this scenario this provide us confidence from possible regressions in future.

**Comment by venkateshwaracholan** [comment]
> Please fix compilation errors and add test

done @martin-gaievski, Please review

**Comment by martin-gaievski** [comment]
> > Please fix compilation errors and add test
> 
> done @martin-gaievski, Please review

can you please use unit tests instead of integration tests? Main reason being they are faster and consume less resources, and for scenario like this this is even more necessary because newly created data will not be used at all. 

For instance, you can create new class `HybridOptimizerExperimentProcessorTests` and add tests for at least these three scenarios:
-  judgment deletion while experiment is running
- thread safety with concurrent failures
- isolation from caller's hasFailure

**Comment by epugh** [comment]
> > > > Please fix compilation errors and add test
> > > 
> > > 
> > > done @martin-gaievski, Please review
> > 
> > 
> > can you please use unit tests instead of integration tests? Main reason being they are faster and consume less resources, and for scenario like this this is even more necessary because newly created data will not be used at all.
> > For instance, you can create new class `HybridOptimizerExperimentProcessorTests` and add tests for at least these three scenarios:
> > 
> > * judgment deletion while experiment is running
> > * thread safety with concurrent failures
> > * isolation from caller's hasFailure
> 
> @martin-gaievski I added the Unit tests,
> 
> Regarding the **caller–callee `hasFailure` isolation test** I initially explored verifying isolation by inspecting the callee’s internal `hasFailure` flag (via reflection or a `@VisibleForTesting` field). However, that approach would require introducing new state (e.g., `lastRunHasFailure`) purely for testing, which would pollute the production class.
> 
> After reviewing the code flow, it’s clear that isolation is **inherently guaranteed by design**:
> 
> * The **caller’s `hasFailure`** is a separate local variable in the experiment orchestration layer.
> * The **callee (`HybridOptimizerExperimentProcessor`)** creates its own local `AtomicBoolean hasFailure` for each experiment run.
> * These are **independent, stack-scoped variables** — they cannot interfere or share state by definition.
> 
> Because of this, adding reflective checks or asserting `assertNotSame(callerHasFailure, calleeHasFailure)` would only confirm something Java already enforces.
> 
> Instead, the test focuses on **observable behavior** — verifying that the caller still receives an `onFailure()` callback even if the callee internally sets its own `hasFailure` flag. This ensures correct failure propagation **without introducing hacky or non-essential testing hooks**.
> 
> Also should i remove the Integration tests since we added unit tests now or it can exist?

My perspective is we should remove the integration tests.  We want the fewest number of tests that still meet our quality expectations since every test is more to maintain, and we have a small volunteer team!

**Comment by venkateshwaracholan** [comment]
@epugh @martin-gaievski removed integration tests
