### PR TITLE
[BUG] Incomplete judgment ratings groups were shown during selection add status filter to List Judgments API to return only relevant judgment states

### LINKED ISSUE #266: [BUG] Incomplete judgment ratings groups are available for selection in create experiment workflow
### What is the bug?
System allows to use judgment rating group that is not ready yet (rating generation is still in process). For example, I can pick such group and start hybrid optimizer experiment. In such case results of such experiment (search relevance metrics like NDCG etc.) will be zeros 

### How can one reproduce the bug?
- Do all prep steps: create index, ingest documents, create query terms, import search configuration with queries for verification of LLM rating generation and hybrid optimizer related query (you'll need it later)
- Start generating judgment ratings with LLM, pick some large number of ratings, in my example I used 50 query terms and 500 ratings (k = 500). Once you started this process, system will create an empty entry for judgment rating group in a status PROCESSING.
- Go to hybrid Search Optimizer, start new experiment, for the judgments pick the newly created rating group, and start the experiment.
- Once experiment is completed, observer the results. All the metrics like NDECG or Precision are 0.0.

### What is the expected behavior?
System should not allow selection of judgment rating group that is not yet completed/still in process.  Alternatively we can leave the current behavior but validate in experiment and fail fast with error.
I prefer the first option, it's more intuitive and gives better UX. For second option, user will see their experiment as failed and will need to monitor progress of rating creation task and create new experiment. 

### What is your host/environment?
OS 3.3

### Do you have any screenshots?
Fresh task for creating ratings with LLM, notice PROCESSING status

Image

This is create experiment screen, I can pick the rating group while it's not yet ready

Image

### PR DESCRIPTION
**Pull request by iprithv**
### Description
This change adds support for filtering judgments by status in the **List Judgments** API.

Previously, the API always returned all judgments regardless of processing state, which caused incomplete or processing judgment groups to appear as selectable options when creating experiments.  
This update introduces an optional `status` query parameter (`COMPLETED`, `PROCESSING`, `ERROR`, `TIMEOUT`) to allow clients to request only judgments in a specific status.

The integration tests were updated to validate filtering behavior for all status types and to ensure that only matching results are returned.

Screenshot 2025-11-06 at 4 04 01 PM

### Issues Resolved
Closes #266 

### Check List
- [x] API updated to support `status` filter
- [x] Status filtering integrated into search query builder
- [x] Integration tests added for each status filter
- [x] Existing test suite verified

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java [hunk 1]
```diff
@@ -32,6 +32,64 @@
 @OpenSearchIntegTestCase.ClusterScope(scope = OpenSearchIntegTestCase.Scope.SUITE)
 public class JudgmentsIT extends BaseSearchRelevanceIT {
 
+    @SuppressWarnings("unchecked")
+    private List<String> extractStatuses(Map<String, Object> result) {
+        Map<String, Object> hitsObj = (Map<String, Object>) result.get("hits");
```
Comment (epugh) [inline src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java]: funny how I see this pattern all over the place!  In our front end code, our tests, etc...  Just a comment!

File: src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java [hunk 2]
```diff
@@ -120,4 +178,46 @@ public void testMainActions_whenImportReadJudgments_thenSuccessful() {
...
+            }
+            """;
+
+        // Create 4 judgments
+        String completedId = createJudgment(createBase);
+        String processingId = createJudgment(createBase);
+        String errorId = createJudgment(createBase);
+        String timeoutId = createJudgment(createBase);
+
+        Thread.sleep(DEFAULT_INTERVAL_MS);
```
Comment (epugh) [inline src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java]: Thread.sleep always makes me nervous, but if this is a pattern we use, then fine!

File: src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java [hunk 3]
```diff
@@ -32,6 +32,64 @@
...
+                JUDGMENTS_URL,
+                filterStatus == null ? null : Map.of("status", filterStatus),
+                null,
+                ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
+            )
+        );
+
+        List<String> statuses = extractStatuses(result);
+
+        // must match exactly if we expect one
```
[the remark this answers is not in the document]
Comment (iprithv) [reply src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java]: the single-value branch is mainly for strict equality validation to ensure we don’t accidentally return extra statuses for filtered queries. When testing the “ALL” case, we intentionally check containsAll since the order may vary. So the split here is to enforce correctness in filtered vs unfiltered scenarios.

**Comment by epugh** [comment]
Once this is merged, then we can merge https://github.com/opensearch-project/dashboards-search-relevance/pull/674

**Comment by epugh** [comment]
@martin-gaievski I'm chatting with @iprithv about this ticket, can you give it a review and make sure it meets what you are expecting in the original issue?

File: src/main/java/org/opensearch/searchrelevance/rest/RestGetJudgmentAction.java [hunk 4]
```diff
@@ -73,6 +73,13 @@ protected RestChannelConsumer prepareRequest(RestRequest request, NodeClient cli
             .size(searchParams.getSize())
             .sort(searchParams.getSortField(), searchParams.getSortOrder());
 
+        String status = request.param("status");
+        if (status != null && !status.isEmpty()) {
+            searchSourceBuilder.query(QueryBuilders.termQuery("status.keyword", status.toUpperCase(Locale.ROOT)));
+        } else {
+            searchSourceBuilder.query(QueryBuilders.matchAllQuery());
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/searchrelevance/rest/RestGetJudgmentAction.java]: this is duplicate of what we do have in line 72:
```
new SearchSourceBuilder().query(QueryBuilders.matchAllQuery())
```

File: src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java [hunk 5]
```diff
@@ -120,4 +179,46 @@ public void testMainActions_whenImportReadJudgments_thenSuccessful() {
...
+        String errorId = createJudgment(createBase);
+        String timeoutId = createJudgment(createBase);
+
+        Thread.sleep(DEFAULT_INTERVAL_MS);
+
+        // Force statuses
+        updateStatus(completedId, "COMPLETED");
+        updateStatus(processingId, "PROCESSING");
+        updateStatus(errorId, "ERROR");
+        updateStatus(timeoutId, "TIMEOUT");
```
Comment (martin-gaievski) [inline src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java]: for last three statuses, looks like we are using integ test to test all possible variants. Let's utilize unit tests for this, integ test are expensive to run and should be reserved for basic end to end scenarios or as a last resort for critical flows.

Comment (iprithv) [reply src/test/java/org/opensearch/searchrelevance/action/judgment/JudgmentsIT.java]: @martin-gaievski Would this simplified version of the integration test be sufficient?
I removed the tests for the other three statuses and kept only the COMPLETED case.
Let me know if you’d prefer adding separate unit tests to cover PROCESSING, ERROR, and TIMEOUT as well.

**Review by martin-gaievski — COMMENTED** [review]
We do need a unit test for RestGetJudgmentAction, please add it and put tests for all permutations of input params

File: src/main/java/org/opensearch/searchrelevance/rest/RestGetJudgmentAction.java [hunk 6]
```diff
@@ -73,6 +73,11 @@ protected RestChannelConsumer prepareRequest(RestRequest request, NodeClient cli
             .size(searchParams.getSize())
             .sort(searchParams.getSortField(), searchParams.getSortOrder());
 
+        String status = request.param("status");
+        if (status != null && !status.isEmpty()) {
+            searchSourceBuilder.query(QueryBuilders.termQuery("status.keyword", status.toUpperCase(Locale.ROOT)));
```
[the remark this answers is not in the document]
Comment (iprithv) [reply src/main/java/org/opensearch/searchrelevance/rest/RestGetJudgmentAction.java]: Updated the logic so that matchAllQuery() is only applied when status is not provided, and termQuery is used when status is present. Removed the unconditional matchAllQuery() from the builder initialisation as suggested.

**Review by epugh — APPROVED** [review]
LGTM.
